apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: customPrefixer
suffix: -__ENV__
fieldSpecs:
  - kind: Ingress
    path: metadata/name
  - kind: Service
    path: metadata/name
  - kind: Rollout
    path: metadata/name
  - kind: Rollout
    path: spec/template/spec/containers/name
